Repository ultralytics/google-images-download, pull requests merged in 2025-01, with the labels that each got.

#41 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#42 Standardize license headers in Python files
  beautiful_scraper.py
  bing_scraper.py
  clean_images.py
Labels: documentation, devops

#43 Standardize license headers in TOML/YAML files
  .github/workflows/format.yml
Labels: documentation, enhancement
